[package]
name = "pagerduty-rust"
version = "0.1.0"
authors = ["Daniel Bowtell <dan@danbowtell.co.uk>"]

[dependencies]
hyper = '0.11.2'
hyper-tls = "0.1.2"
rustc-serialize = '0.3'
tokio-core = "0.1"
futures = "0.1"
serde_json = "1.0"