#!/bin/sh

if [ $BLOCK_BUTTON = "1" ]; then
    ~/dotfiles/system_scripts/active_port.sh > /dev/null
fi


DEVICE='alsa_output.pci-0000_00_14.2.analog-stereo'
ACTIVE_SINK=$(pacmd list-sinks | grep 'active port' | grep 'analog' | awk '{ print $3 }' | head -n1)

if [ "$ACTIVE_SINK" = "<analog-output-headphones>" ]; then
	echo ""
else
	echo "🔈"
fi

exit 0
